openapi: "3.0.1"

info:
  title: Tsuki API
  version: "1.0"
  description: Tsuki backend API

paths:
  /health:
    get:
      operationId: healthCheck
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        payloadFormatVersion: "2.0"
        uri: ${LAMBDA_URI_USERMANAGEMENT}
      responses:
        "200":
          description: OK

  /auth/register:
    post:
      operationId: register
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        payloadFormatVersion: "2.0"
        uri: ${LAMBDA_URI_USERMANAGEMENT}
      responses:
        "200":
          description: OK

  /auth/login:
    post:
      operationId: login
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        payloadFormatVersion: "2.0"
        uri: ${LAMBDA_URI_USERMANAGEMENT}
      responses:
        "200":
          description: OK

  /auth/verify:
    post:
      operationId: verify
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        payloadFormatVersion: "2.0"
        uri: ${LAMBDA_URI_USERMANAGEMENT}
      responses:
        "200":
          description: OK
  /metadata/health:
    get:
      operationId: healthCheck
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        payloadFormatVersion: "2.0"
        uri: ${LAMBDA_URI_PLAYERMETADATA}
      responses:
        "200":
          description: OK
