service: tsuki-usermanagement

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  httpApi:
    id: mjcxtv3yse
    payload: "2.0"

  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
    CLIENT_ID: ${env:CLIENT_ID}

functions:
  api:
    handler: handler.handler
    name: tsuki-usermanagement
    events:
      - httpApi:
          method: GET
          path: /health
      - httpApi:
          method: POST
          path: /auth/register
      - httpApi:
          method: POST
          path: /auth/login
      - httpApi:
          method: POST
          path: /auth/verify
