service: tsuki-usermanagement

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
    CLIENT_ID: ${env:CLIENT_ID}

functions:
  api:
    name: tsuki-usermanagement
    handler: handler.handler
