service: tsuki-playermetadata

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

  environment:

functions:
  api:
    name: tsuki-playermetadata
    handler: handler.handler
