service: tsuki-playermetadata

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  api:
    name: tsuki-playermetadata
    handler: handler.handler
    timeout: 30
    memorySize: 1024
