service: tsuki-playable
frameworkVersion: "3"
provider:
  name: aws
  runtime: python3.12
  region: ap-south-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer: true

functions:
  api:
    name: tsuki-playable
    handler: handler.lambda_handler
    timeout: 30
    memorySize: 1024
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

resources:
  Resources:
    PlayableApiGatewayPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !Ref ApiLambdaFunction
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*"
