service: tsuki-playable

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer: true

functions:
  api:
    name: tsuki-playable
    handler: handler.lambda_handler
    timeout: 60
    memorySize: 1536
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
